export default function decorate(block) {
  console.log('VAULTORA DYNAMIC HEADER DECORATION');

  block.classList.add('vaultora-header');

  // Grab sections generated by the native boilerplate code
  const navBrand = block.querySelector('.nav-brand');
  const navSections = block.querySelector('.nav-sections');
  const navTools = block.querySelector('.nav-tools');

  if (navBrand) navBrand.classList.add('header-logo');
  if (navSections) navSections.classList.add('header-nav');
  
  if (navTools) {
    navTools.classList.add('header-actions');

    // 1. Handle Role-Based Conditional Text for the CTA button
    const ctaButton = navTools.querySelector('a, li'); 
    const session = JSON.parse(localStorage.getItem('Vaultora_session')) || null;

    if (session && session.role && ctaButton) {
      const role = session.role.toLowerCase();
      
      if (role === 'buy') {
        ctaButton.textContent = 'BUY NOW';
      } else if (role === 'sell') {
        ctaButton.textContent = 'SELL NOW';
      } else if (role === 'both' || role === 'can sell or buy') {
        ctaButton.textContent = 'BUY & SELL NOW';
      }
    }

    // 2. Setup or isolate the profile container
    let profileCol = navTools.querySelector('.header-profile');
    if (!profileCol) {
      profileCol = document.createElement('div');
      profileCol.classList.add('header-profile');
      navTools.appendChild(profileCol);
    }

    // 3. Conditional Authentication Rendering (Matches image_1e6780.png)
    if (session) {
      const displayName = session.name || session.email || 'User';
      const initial = displayName.charAt(0).toUpperCase();

      // Logged-in State Layout
      profileCol.innerHTML = `
        <div class="user-chip">
          <div class="user-avatar">${initial}</div>
          <span class="user-name">${displayName}</span>
        </div>
        <button class="logout-btn">Logout</button>
      `;

      // Event listener for signing out
      profileCol.querySelector('.logout-btn')?.addEventListener('click', () => {
        localStorage.removeItem('Vaultora_session');
        window.location.href = '/login'; 
      });

    } else {
      // Logged-out State Layout
      profileCol.innerHTML = `
        <a href="/register" class="get-started-btn">Get Started for Free</a>
      `;
    }
  }

  // Mobile hamburger linkage
  const hamburger = block.querySelector('.nav-hamburger');
  if (hamburger && navSections) {
    hamburger.addEventListener('click', () => {
      navSections.classList.toggle('open');
    });
  }
}